import type { DestinationInfo, Place } from "./types";

export interface DestinationDataset {
  info: DestinationInfo;
  places: Place[];
}

export const CURATED_DESTINATIONS: Record<string, DestinationDataset> = {
  goa: {
    info: {
      slug: "goa",
      name: "Goa",
      country: "India",
      description:
        "India's premier coastal haven, celebrated for its sun-kissed Arabian Sea beaches, Portuguese colonial architecture, vibrant spice plantations, and laid-back tropical vibe.",
      bestTimeToVisit: "November to March (pleasant coastal breeze & sunny skies)",
      coordinates: { latitude: 15.2993, longitude: 74.124 },
      heroImageUrl:
        "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?q=80&w=1200&auto=format&fit=crop",
      popularCategories: ["relaxation", "nature", "food", "culture", "nightlife", "adventure", "attractions"],
      totalPlaces: 8,
    },
    places: [
      {
        id: "goa-basilica-bom-jesus",
        slug: "basilica-of-bom-jesus",
        name: "Basilica of Bom Jesus",
        destination: "Goa",
        destinationSlug: "goa",
        category: "culture",
        description:
          "A UNESCO World Heritage site and monumental exemplar of baroque architecture in Old Goa, housing the sacred mortal remains of St. Francis Xavier.",
        shortDescription: "16th-century UNESCO World Heritage church with baroque architecture.",
        rating: 4.8,
        reviewCount: 14200,
        priceLevel: "free",
        address: "Old Goa Road, Bainguinim, Goa 403402",
        coordinates: { latitude: 15.5009, longitude: 73.9116 },
        imageUrl:
          "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?q=80&w=800&auto=format&fit=crop",
        tags: ["UNESCO", "Heritage", "History", "Baroque"],
        openingHours: "9:00 AM - 6:30 PM",
      },
      {
        id: "goa-palolem-beach",
        slug: "palolem-beach",
        name: "Palolem Beach",
        destination: "Goa",
        destinationSlug: "goa",
        category: "relaxation",
        description:
          "A serene, crescent-shaped bay lined with leaning coconut palms, colorful beach huts, and gentle tides ideal for swimming, dolphin spotting, and sunset watching.",
        shortDescription: "Scenic crescent bay known for tranquil waters and pastel wooden cottages.",
        rating: 4.7,
        reviewCount: 18500,
        priceLevel: "budget",
        address: "Canacona, South Goa 403702",
        coordinates: { latitude: 15.0101, longitude: 74.0232 },
        imageUrl:
          "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=800&auto=format&fit=crop",
        tags: ["Beach", "Sunset", "Scenic", "Swimming"],
        openingHours: "Open 24 hours",
      },
      {
        id: "goa-dudhsagar-falls",
        slug: "dudhsagar-waterfalls",
        name: "Dudhsagar Waterfalls",
        destination: "Goa",
        destinationSlug: "goa",
        category: "nature",
        description:
          "One of India's tallest four-tiered waterfalls located on the Mandovi River, plunging through lush Western Ghats tropical jungle in a dramatic cascade of white foam.",
        shortDescription: "Spectacular four-tiered 310-meter waterfall inside Bhagwan Mahaveer Sanctuary.",
        rating: 4.7,
        reviewCount: 11300,
        priceLevel: "budget",
        address: "Sonaulim, Bhagwan Mahaveer Sanctuary, Goa 403410",
        coordinates: { latitude: 15.3144, longitude: 74.3143 },
        imageUrl:
          "https://images.unsplash.com/photo-1544644181-1484b3fdfc62?q=80&w=800&auto=format&fit=crop",
        tags: ["Waterfalls", "Nature", "Jungle", "Scenic Trek"],
        openingHours: "8:30 AM - 4:30 PM",
      },
      {
        id: "goa-aguada-fort",
        slug: "aguada-fort",
        name: "Fort Aguada & Lighthouse",
        destination: "Goa",
        destinationSlug: "goa",
        category: "attractions",
        description:
          "A well-preserved 17th-century Portuguese coastal fortification overlooking Sinquerim Beach and the Arabian Sea, featuring an iconic freshwater spring and historic lighthouse.",
        shortDescription: "Historic 17th-century clifftop fortress with panoramic ocean views.",
        rating: 4.5,
        reviewCount: 22400,
        priceLevel: "budget",
        address: "Aguada Fort Rd, Candolim, Goa 403515",
        coordinates: { latitude: 15.4925, longitude: 73.7735 },
        imageUrl:
          "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?q=80&w=800&auto=format&fit=crop",
        tags: ["Historic Fort", "Coastal Views", "Portuguese Era", "Landmark"],
        openingHours: "9:30 AM - 6:00 PM",
      },
      {
        id: "goa-thalassa",
        slug: "thalassa-siolim",
        name: "Thalassa Mediterranean Dining",
        destination: "Goa",
        destinationSlug: "goa",
        category: "food",
        description:
          "Legendary open-air restaurant perched along the waterfront in Siolim, renowned for fresh seafood souvlaki, sunset views, and lively Mediterranean hospitality.",
        shortDescription: "Beloved waterfront dining celebrated for Greek and Goan fusion flavors.",
        rating: 4.6,
        reviewCount: 9800,
        priceLevel: "moderate",
        address: "Vaddy, Siolim, Goa 403517",
        coordinates: { latitude: 15.6267, longitude: 73.7661 },
        imageUrl:
          "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?q=80&w=800&auto=format&fit=crop",
        tags: ["Seafood", "Sunset Dining", "Greek", "Cocktails"],
        openingHours: "12:00 PM - 1:00 AM",
      },
      {
        id: "goa-grand-island-scuba",
        slug: "grand-island-scuba",
        name: "Grand Island Scuba & Snorkeling",
        destination: "Goa",
        destinationSlug: "goa",
        category: "adventure",
        description:
          "The premier marine excursion in Goa, offering guided reef dives, shipwrecks, rich underwater fauna, and kayaking tours off the coast of Vasco da Gama.",
        shortDescription: "Top marine adventure featuring coral reef diving, shipwrecks, and boat tours.",
        rating: 4.6,
        reviewCount: 5200,
        priceLevel: "moderate",
        address: "Boat launch from Sinquerim Jetty, Goa 403515",
        coordinates: { latitude: 15.3532, longitude: 73.7725 },
        imageUrl:
          "https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=800&auto=format&fit=crop",
        tags: ["Scuba Diving", "Reefs", "Watersports", "Boat Excursion"],
        openingHours: "6:30 AM - 3:00 PM",
      },
      {
        id: "goa-anjuna-curlies",
        slug: "curlies-beach-shack",
        name: "Curlies & Anjuna Beachfront",
        destination: "Goa",
        destinationSlug: "goa",
        category: "nightlife",
        description:
          "Iconic North Goa open-air venue on South Anjuna beach offering sunset cocktails, international DJs, live percussion, and eclectic coastal nightlife vibes.",
        shortDescription: "Legendary beach lounge and sunset nightlife destination on Anjuna beach.",
        rating: 4.4,
        reviewCount: 16100,
        priceLevel: "moderate",
        address: "Anjuna Beach, Monteiro Vaddo, Anjuna, Goa 403509",
        coordinates: { latitude: 15.5739, longitude: 73.7412 },
        imageUrl:
          "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?q=80&w=800&auto=format&fit=crop",
        tags: ["Live Music", "Beach Club", "Nightlife", "Sunset Cocktails"],
        openingHours: "11:00 AM - 3:00 AM",
      },
      {
        id: "goa-sahakari-spice-farm",
        slug: "sahakari-spice-farm",
        name: "Sahakari Spice Farm",
        destination: "Goa",
        destinationSlug: "goa",
        category: "nature",
        description:
          "An organic, 130-acre agricultural sanctuary showcasing cardamom, cinnamon, vanilla, and betel nut cultivation, concluding with a traditional Goan buffet served on banana leaves.",
        shortDescription: "Lush tropical plantation tour with traditional organic Goan herbal lunch.",
        rating: 4.5,
        reviewCount: 7100,
        priceLevel: "budget",
        address: "Curti, Ponda, Goa 403401",
        coordinates: { latitude: 15.4181, longitude: 74.0289 },
        imageUrl:
          "https://images.unsplash.com/photo-1509358271058-acd22cc93898?q=80&w=800&auto=format&fit=crop",
        tags: ["Spice Plantation", "Eco Tour", "Organic Food", "Botanical"],
        openingHours: "9:00 AM - 4:30 PM",
      },
    ],
  },
  tokyo: {
    info: {
      slug: "tokyo",
      name: "Tokyo",
      country: "Japan",
      description:
        "An exhilarating metropolis where ultra-modern technology and neon skyscrapers seamlessly converge with ancient Shinto shrines, historic tea gardens, and world-class gastronomy.",
      bestTimeToVisit: "March to May (Cherry blossoms) & October to November (Autumn foliage)",
      coordinates: { latitude: 35.6762, longitude: 139.6503 },
      heroImageUrl:
        "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?q=80&w=1200&auto=format&fit=crop",
      popularCategories: ["culture", "food", "attractions", "nature", "nightlife", "relaxation", "adventure"],
      totalPlaces: 7,
    },
    places: [
      {
        id: "tokyo-sensoji",
        slug: "senso-ji-temple",
        name: "Senso-ji Temple",
        destination: "Tokyo",
        destinationSlug: "tokyo",
        category: "culture",
        description:
          "Tokyo's oldest and most renowned Buddhist temple in historic Asakusa, entered through the striking Kaminarimon Thunder Gate and vibrant Nakamise shopping street.",
        shortDescription: "Ancient Buddhist temple dating back to 645 AD in historic Asakusa.",
        rating: 4.8,
        reviewCount: 38200,
        priceLevel: "free",
        address: "2 Chome-3-1 Asakusa, Taito City, Tokyo 111-0032",
        coordinates: { latitude: 35.7148, longitude: 139.7967 },
        imageUrl:
          "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?q=80&w=800&auto=format&fit=crop",
        tags: ["Historic Temple", "Culture", "Architecture", "Asakusa"],
        openingHours: "6:00 AM - 5:00 PM",
      },
      {
        id: "tokyo-shibuya-sky",
        slug: "shibuya-sky-crossing",
        name: "Shibuya Sky & The Crossing",
        destination: "Tokyo",
        destinationSlug: "tokyo",
        category: "attractions",
        description:
          "A 360-degree open-air rooftop observation deck 229 meters above Shibuya, providing breathtaking panoramas of Mount Fuji, the famous scramble crossing, and the Tokyo skyline.",
        shortDescription: "Iconic open-air rooftop observatory over the world's busiest pedestrian crossing.",
        rating: 4.9,
        reviewCount: 29500,
        priceLevel: "moderate",
        address: "2 Chome-24-12 Shibuya, Shibuya City, Tokyo 150-0002",
        coordinates: { latitude: 35.6598, longitude: 139.7024 },
        imageUrl:
          "https://images.unsplash.com/photo-1542051841857-5f90071e7989?q=80&w=800&auto=format&fit=crop",
        tags: ["Observation Deck", "Skyline Views", "Iconic Landmark", "Modern"],
        openingHours: "10:00 AM - 10:30 PM",
      },
      {
        id: "tokyo-tsukiji",
        slug: "tsukiji-outer-market",
        name: "Tsukiji Outer Market",
        destination: "Tokyo",
        destinationSlug: "tokyo",
        category: "food",
        description:
          "A lively labyrinth of hundreds of traditional vendors, seafood stalls, knife craftsmen, and specialty sushi counters serving the freshest tuna sashimi, tamagoyaki, and wagyu skewers.",
        shortDescription: "World-famous culinary district packed with street food and authentic sushi.",
        rating: 4.7,
        reviewCount: 24600,
        priceLevel: "budget",
        address: "4 Chome-16-2 Tsukiji, Chuo City, Tokyo 104-0045",
        coordinates: { latitude: 35.6655, longitude: 139.7707 },
        imageUrl:
          "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?q=80&w=800&auto=format&fit=crop",
        tags: ["Street Food", "Fresh Seafood", "Sushi", "Authentic Culinary"],
        openingHours: "5:00 AM - 2:00 PM",
      },
      {
        id: "tokyo-shinjuku-gyoen",
        slug: "shinjuku-gyoen-garden",
        name: "Shinjuku Gyoen National Garden",
        destination: "Tokyo",
        destinationSlug: "tokyo",
        category: "nature",
        description:
          "One of Tokyo's largest and most tranquil historic parks, harmonizing traditional Japanese landscape gardens, English lawns, French formal flower gardens, and seasonal cherry blossoms.",
        shortDescription: "Expansive oasis featuring tranquil ponds, tea houses, and 1,000 cherry trees.",
        rating: 4.8,
        reviewCount: 31200,
        priceLevel: "budget",
        address: "11 Naitomachi, Shinjuku City, Tokyo 160-0014",
        coordinates: { latitude: 35.6852, longitude: 139.71 },
        imageUrl:
          "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?q=80&w=800&auto=format&fit=crop",
        tags: ["Botanical Garden", "Cherry Blossoms", "Serene", "Japanese Garden"],
        openingHours: "9:00 AM - 4:00 PM (Closed Mondays)",
      },
      {
        id: "tokyo-golden-gai",
        slug: "golden-gai-shinjuku",
        name: "Shinjuku Golden Gai",
        destination: "Tokyo",
        destinationSlug: "tokyo",
        category: "nightlife",
        description:
          "A compact network of six narrow alleys lined with over 200 tiny, atmospheric bars and micro-lounges that preserved the architectural character of post-war Tokyo.",
        shortDescription: "Intimate district of over 200 historic micro-bars and themed music venues.",
        rating: 4.6,
        reviewCount: 14800,
        priceLevel: "moderate",
        address: "1 Chome-1-6 Kabukicho, Shinjuku City, Tokyo 160-0021",
        coordinates: { latitude: 35.6942, longitude: 139.7046 },
        imageUrl:
          "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=800&auto=format&fit=crop",
        tags: ["Micro Bars", "Nightlife", "Kabukicho", "Historic Alleys"],
        openingHours: "7:00 PM - 4:00 AM",
      },
      {
        id: "tokyo-mount-takao",
        slug: "mount-takao-trail",
        name: "Mount Takao Hiking Trails",
        destination: "Tokyo",
        destinationSlug: "tokyo",
        category: "adventure",
        description:
          "Located just 50 minutes from central Tokyo, this revered mountain offers scenic alpine trails, a mountaintop Buddhist temple, monkey park, and unobstructed views of Mount Fuji on clear days.",
        shortDescription: "Accessible mountain adventure with panoramic views and historic shrines.",
        rating: 4.7,
        reviewCount: 18900,
        priceLevel: "free",
        address: "Takaomachi, Hachioji, Tokyo 193-0844",
        coordinates: { latitude: 35.6251, longitude: 139.2437 },
        imageUrl:
          "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=800&auto=format&fit=crop",
        tags: ["Mountain Trek", "Hiking", "Mt Fuji Views", "Adventure"],
        openingHours: "Open 24 hours (Cable car: 8:00 AM - 5:45 PM)",
      },
      {
        id: "tokyo-onsen-niwa",
        slug: "thermae-yu-onsen",
        name: "Thermae-Yu Natural Onsen Spa",
        destination: "Tokyo",
        destinationSlug: "tokyo",
        category: "relaxation",
        description:
          "A luxurious urban onsen complex in Shinjuku featuring natural spring water brought daily from Izu, mineral baths, cypress saunas, and tranquil lounge pavilions.",
        shortDescription: "Rejuvenating thermal spring baths and wellness spa in the heart of the city.",
        rating: 4.6,
        reviewCount: 6500,
        priceLevel: "moderate",
        address: "1 Chome-1-2 Kabukicho, Shinjuku City, Tokyo 160-0021",
        coordinates: { latitude: 35.6949, longitude: 139.7058 },
        imageUrl:
          "https://images.unsplash.com/photo-1540555700478-4be289fbecef?q=80&w=800&auto=format&fit=crop",
        tags: ["Thermal Springs", "Wellness", "Sauna", "Relaxation"],
        openingHours: "Open 24 hours",
      },
    ],
  },
  paris: {
    info: {
      slug: "paris",
      name: "Paris",
      country: "France",
      description:
        "The City of Light, celebrated globally for its romantic Haussmann boulevards, iconic monuments, world-leading art institutions, exquisite pastries, and rich literary heritage.",
      bestTimeToVisit: "April to June & September to October (Mild weather & outdoor café culture)",
      coordinates: { latitude: 48.8566, longitude: 2.3522 },
      heroImageUrl:
        "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?q=80&w=1200&auto=format&fit=crop",
      popularCategories: ["culture", "attractions", "food", "relaxation", "nightlife", "nature", "adventure"],
      totalPlaces: 6,
    },
    places: [
      {
        id: "paris-eiffel-tower",
        slug: "eiffel-tower",
        name: "Eiffel Tower & Champ de Mars",
        destination: "Paris",
        destinationSlug: "paris",
        category: "attractions",
        description:
          "Gustave Eiffel's 330-meter wrought-iron masterpiece constructed for the 1889 Exposition Universelle, offering unparalleled vistas across the Parisian skyline and the Seine.",
        shortDescription: "The timeless wrought-iron icon of France with panoramic observation decks.",
        rating: 4.8,
        reviewCount: 145000,
        priceLevel: "moderate",
        address: "Champ de Mars, 5 Av. Anatole France, 75007 Paris",
        coordinates: { latitude: 48.8584, longitude: 2.2945 },
        imageUrl:
          "https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?q=80&w=800&auto=format&fit=crop",
        tags: ["Global Landmark", "Skyline", "Observation Deck", "Historic"],
        openingHours: "9:00 AM - 11:45 PM",
      },
      {
        id: "paris-louvre",
        slug: "louvre-museum",
        name: "The Louvre Museum",
        destination: "Paris",
        destinationSlug: "paris",
        category: "culture",
        description:
          "The world's largest museum and former royal palace, housing over 35,000 works of art spanning eight millennia, including Da Vinci's Mona Lisa and the Winged Victory of Samothrace.",
        shortDescription: "World's preeminent art museum housed within a magnificent former royal palace.",
        rating: 4.8,
        reviewCount: 120000,
        priceLevel: "moderate",
        address: "Rue de Rivoli, 75001 Paris",
        coordinates: { latitude: 48.8606, longitude: 2.3376 },
        imageUrl:
          "https://images.unsplash.com/photo-1499856871958-5b9627545d1a?q=80&w=800&auto=format&fit=crop",
        tags: ["Art Museum", "Mona Lisa", "Royal Palace", "Culture"],
        openingHours: "9:00 AM - 6:00 PM (Wed & Fri until 9:45 PM; Closed Tuesdays)",
      },
      {
        id: "paris-le-marais-food",
        slug: "le-marais-bakeries",
        name: "Le Marais Culinary Walk",
        destination: "Paris",
        destinationSlug: "paris",
        category: "food",
        description:
          "A celebrated gastronomic enclave known for historic patisseries, warm artisan baguettes, authentic falafel along Rue des Rosiers, and third-wave espresso roasteries.",
        shortDescription: "Charming historic district filled with premier French bakeries and gourmet delis.",
        rating: 4.7,
        reviewCount: 18400,
        priceLevel: "budget",
        address: "Rue des Rosiers, 75004 Paris",
        coordinates: { latitude: 48.8575, longitude: 2.3592 },
        imageUrl:
          "https://images.unsplash.com/photo-1509440159596-0249088772ff?q=80&w=800&auto=format&fit=crop",
        tags: ["Patisserie", "Street Food", "Bakeries", "Local Flavors"],
        openingHours: "8:00 AM - 8:00 PM",
      },
      {
        id: "paris-jardin-luxembourg",
        slug: "jardin-du-luxembourg",
        name: "Jardin du Luxembourg",
        destination: "Paris",
        destinationSlug: "paris",
        category: "relaxation",
        description:
          "Created in 1612 by Marie de' Medici, this 25-hectare formal park features gravel pathways, Medici Fountain, green vintage lawn chairs, and peaceful chestnut groves.",
        shortDescription: "Historic 17th-century Medici gardens with quiet fountains and shaded promenades.",
        rating: 4.7,
        reviewCount: 35000,
        priceLevel: "free",
        address: "75006 Paris",
        coordinates: { latitude: 48.8462, longitude: 2.3372 },
        imageUrl:
          "https://images.unsplash.com/photo-1549144511-f099e773c147?q=80&w=800&auto=format&fit=crop",
        tags: ["Palace Gardens", "Fountains", "Picnic", "Tranquil Walk"],
        openingHours: "7:30 AM - Dusk",
      },
      {
        id: "paris-montmartre-cabarets",
        slug: "montmartre-bohemian-evening",
        name: "Montmartre Bohemian Quarter & Cabarets",
        destination: "Paris",
        destinationSlug: "paris",
        category: "nightlife",
        description:
          "The artistic hilltop district crowned by Sacré-Cœur, filled with vintage jazz bars, street painters on Place du Tertre, wine bistros, and iconic music halls.",
        shortDescription: "Hilltop bohemian neighborhood brimming with wine bars and live jazz music.",
        rating: 4.6,
        reviewCount: 28000,
        priceLevel: "moderate",
        address: "Place du Tertre, 75018 Paris",
        coordinates: { latitude: 48.8867, longitude: 2.3431 },
        imageUrl:
          "https://images.unsplash.com/photo-1508009603885-50cf7c579365?q=80&w=800&auto=format&fit=crop",
        tags: ["Live Jazz", "Wine Bars", "Sacre-Coeur", "Historic Nightlife"],
        openingHours: "6:00 PM - 2:00 AM",
      },
      {
        id: "paris-seine-kayak",
        slug: "bois-de-boulogne-trails",
        name: "Bois de Boulogne Trails & Lakes",
        destination: "Paris",
        destinationSlug: "paris",
        category: "nature",
        description:
          "Paris's vast western woodland park, two and a half times larger than Central Park in New York, offering rowing boats on Lower Lake, cycling paths, and peaceful waterfalls.",
        shortDescription: "Vast woodland reserve featuring scenic lakes, rowboats, and forest trails.",
        rating: 4.5,
        reviewCount: 9200,
        priceLevel: "free",
        address: "75016 Paris",
        coordinates: { latitude: 48.8624, longitude: 2.2494 },
        imageUrl:
          "https://images.unsplash.com/photo-1448375240586-882707db888b?q=80&w=800&auto=format&fit=crop",
        tags: ["Forest Trails", "Boating Lake", "Nature", "Cycling"],
        openingHours: "Open 24 hours",
      },
    ],
  },
  bali: {
    info: {
      slug: "bali",
      name: "Bali",
      country: "Indonesia",
      description:
        "The famed Island of the Gods, renowned for volcanic mountain peaks, terraced emerald rice paddies, spiritual Hindu temples, and world-class surfing along rugged coastlines.",
      bestTimeToVisit: "April to October (Dry season with low humidity)",
      coordinates: { latitude: -8.4095, longitude: 115.1889 },
      heroImageUrl:
        "https://images.unsplash.com/photo-1537996194471-e657df975ab4?q=80&w=1200&auto=format&fit=crop",
      popularCategories: ["nature", "culture", "relaxation", "adventure", "food", "nightlife", "attractions"],
      totalPlaces: 6,
    },
    places: [
      {
        id: "bali-uluwatu-temple",
        slug: "uluwatu-temple",
        name: "Uluwatu Clifftop Temple",
        destination: "Bali",
        destinationSlug: "bali",
        category: "culture",
        description:
          "An ancient Balinese sea temple perched on a dramatic 70-meter limestone cliff overlooking the crashing waves of the Indian Ocean, famous for evening Kecak fire dances.",
        shortDescription: "Spectacular 11th-century sea temple perched 70 meters above the ocean.",
        rating: 4.8,
        reviewCount: 42000,
        priceLevel: "budget",
        address: "Pecatu, South Kuta, Badung Regency, Bali",
        coordinates: { latitude: -8.8291, longitude: 115.0849 },
        imageUrl:
          "https://images.unsplash.com/photo-1555400038-63f5ba517a47?q=80&w=800&auto=format&fit=crop",
        tags: ["Sea Temple", "Kecak Dance", "Sunset View", "Historic"],
        openingHours: "7:00 AM - 7:00 PM",
      },
      {
        id: "bali-tegallalang",
        slug: "tegallalang-rice-terraces",
        name: "Tegallalang Rice Terraces",
        destination: "Bali",
        destinationSlug: "bali",
        category: "nature",
        description:
          "Sculpted valley of terraced emerald-green rice paddies in Ubud employing the ancient traditional Balinese cooperative irrigation system known as Subak.",
        shortDescription: "Iconic emerald rice terraces in the lush highland hills of Ubud.",
        rating: 4.6,
        reviewCount: 36000,
        priceLevel: "budget",
        address: "Jl. Raya Tegallalang, Gianyar, Bali 80561",
        coordinates: { latitude: -8.4334, longitude: 115.2778 },
        imageUrl:
          "https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?q=80&w=800&auto=format&fit=crop",
        tags: ["Rice Terraces", "Subak UNESCO", "Scenic Valley", "Nature"],
        openingHours: "8:00 AM - 6:00 PM",
      },
      {
        id: "bali-mount-batur",
        slug: "mount-batur-trek",
        name: "Mount Batur Sunrise Trek",
        destination: "Bali",
        destinationSlug: "bali",
        category: "adventure",
        description:
          "An active volcanic peak standing 1,717 meters above sea level, offering early morning hikers an unforgettable sunrise above a sea of clouds and Lake Batur.",
        shortDescription: "Guided early morning volcano hike with panoramic sunrise above the clouds.",
        rating: 4.8,
        reviewCount: 22000,
        priceLevel: "moderate",
        address: "South Batur, Kintamani, Bangli Regency, Bali 80652",
        coordinates: { latitude: -8.242, longitude: 115.3752 },
        imageUrl:
          "https://images.unsplash.com/photo-1506744038136-46273834b3fb?q=80&w=800&auto=format&fit=crop",
        tags: ["Volcano Trek", "Sunrise Hike", "Highlands", "Adventure"],
        openingHours: "Tours depart 2:00 AM - 3:00 AM",
      },
      {
        id: "bali-seminyak-club",
        slug: "seminyak-coastal-lounges",
        name: "Seminyak Beachfront Lounges",
        destination: "Bali",
        destinationSlug: "bali",
        category: "nightlife",
        description:
          "A celebrated stretch of sunset bars and open-air beach clubs featuring daybeds, tropical mixology, ambient house music, and direct oceanfront sunset views.",
        shortDescription: "Vibrant coastal nightlife strip with sunset cocktail lounges and beach clubs.",
        rating: 4.6,
        reviewCount: 19500,
        priceLevel: "moderate",
        address: "Seminyak Beach, Badung Regency, Bali",
        coordinates: { latitude: -8.6913, longitude: 115.1524 },
        imageUrl:
          "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=800&auto=format&fit=crop",
        tags: ["Beach Clubs", "Sunset Drinks", "Nightlife", "Oceanfront"],
        openingHours: "10:00 AM - 1:00 AM",
      },
      {
        id: "bali-sanur-beach",
        slug: "sanur-tranquil-coast",
        name: "Sanur Peaceful Promenade",
        destination: "Bali",
        destinationSlug: "bali",
        category: "relaxation",
        description:
          "A 5-kilometer paved seaside path bordered by peaceful reef-sheltered waters, traditional fishing boats (jukung), beachfront warungs, and yoga gazebos.",
        shortDescription: "Gentle coastal promenade perfect for calm swims, sunrise walks, and seaside cafes.",
        rating: 4.7,
        reviewCount: 15400,
        priceLevel: "free",
        address: "Sanur, Denpasar Selatan, Bali 80228",
        coordinates: { latitude: -8.7058, longitude: 115.2625 },
        imageUrl:
          "https://images.unsplash.com/photo-1512100356356-de1b84283e18?q=80&w=800&auto=format&fit=crop",
        tags: ["Calm Waters", "Promenade", "Sunrise Walk", "Relaxation"],
        openingHours: "Open 24 hours",
      },
      {
        id: "bali-ubud-food",
        slug: "ubud-organic-dining",
        name: "Ubud Farm-to-Table & Traditional Warungs",
        destination: "Bali",
        destinationSlug: "bali",
        category: "food",
        description:
          "The heart of Balinese culinary innovation, featuring fragrant roasted suckling pig (Babi Guling), coconut lawar, vegan permaculture cafes, and herbal wellness teas.",
        shortDescription: "Culinary hub renowned for authentic Balinese specialties and organic cafes.",
        rating: 4.8,
        reviewCount: 13900,
        priceLevel: "budget",
        address: "Jl. Suweta, Ubud, Gianyar, Bali 80571",
        coordinates: { latitude: -8.5069, longitude: 115.2625 },
        imageUrl:
          "https://images.unsplash.com/photo-1562967914-608f82629710?q=80&w=800&auto=format&fit=crop",
        tags: ["Balinese Flavors", "Organic", "Warung", "Culinary"],
        openingHours: "10:00 AM - 10:00 PM",
      },
    ],
  },
};

/**
 * Returns a fallback destination for unknown queries with realistic placeholders.
 */
export function generateGenericDestination(slug: string, rawTitle: string): DestinationDataset {
  const coordinates = { latitude: 20.0, longitude: 0.0 };
  const categories: Place["category"][] = [
    "culture",
    "food",
    "nature",
    "attractions",
    "relaxation",
    "adventure",
    "nightlife",
  ];

  const places: Place[] = categories.map((cat, idx) => ({
    id: `${slug}-${cat}-${idx}`,
    slug: `${slug}-${cat}-highlight`,
    name: `${rawTitle} ${cat.charAt(0).toUpperCase() + cat.slice(1)} Discovery`,
    destination: rawTitle,
    destinationSlug: slug,
    category: cat,
    description: `A notable ${cat} highlight in ${rawTitle}, recommended for travelers seeking authentic experiences and memorable discoveries.`,
    shortDescription: `Curated ${cat} highlight in ${rawTitle}.`,
    rating: Number((4.3 + (idx % 6) * 0.1).toFixed(1)),
    reviewCount: 1200 + idx * 450,
    priceLevel: idx % 3 === 0 ? "free" : idx % 2 === 0 ? "moderate" : "budget",
    address: `Central District, ${rawTitle}`,
    coordinates: {
      latitude: coordinates.latitude + (idx * 0.02 - 0.05),
      longitude: coordinates.longitude + (idx * 0.02 - 0.05),
    },
    imageUrl:
      "https://images.unsplash.com/photo-1488646953014-85cb44e25828?q=80&w=800&auto=format&fit=crop",
    tags: [cat, "Highlight", "Must Visit"],
    openingHours: "9:00 AM - 6:00 PM",
  }));

  return {
    info: {
      slug,
      name: rawTitle,
      country: "Global Destination",
      description: `Explore the vibrant neighborhoods, cultural landmarks, and hidden culinary spots of ${rawTitle}.`,
      bestTimeToVisit: "Spring and Autumn for mild temperatures and outdoor exploration",
      coordinates,
      heroImageUrl:
        "https://images.unsplash.com/photo-1488646953014-85cb44e25828?q=80&w=1200&auto=format&fit=crop",
      popularCategories: ["culture", "food", "attractions", "nature", "relaxation"],
      totalPlaces: places.length,
    },
    places,
  };
}
